Update Jenkinsfile3

diff --git a/Jenkinsfile3 b/Jenkinsfile3
--- a/Jenkinsfile3
+++ b/Jenkinsfile3
@@ -18,36 +18,35 @@ pipeline {
       }
     }
 
-     stage('Smoke test') {
+  stage('Smoke test') {
   steps {
     sh '''
       # Clean up old container if it exists
       docker rm -f myapp4-smoke || true
 
-      # Run container for smoke test on a different port than production
+      # Run container for smoke test on a different port
       docker run -d -p 8082:80 --name myapp4-smoke ${IMAGE_NAME}:${BUILD_NUMBER}
 
-      # give container a few seconds to start
       sleep 15
 
-      # simple HTTP check – fail pipeline if non-200
       set +e
       curl -f http://localhost:8082/ > /dev/null 2>&1
       STATUS=$?
       set -e
 
-      # Always clean up the smoke-test container
-      docker rm -f myapp4-smoke || true
-
       if [ "$STATUS" -ne 0 ]; then
-        echo "Smoke test FAILED"
+        echo "Smoke test FAILED, container logs:"
+        docker logs myapp4-smoke || true
+        docker rm -f myapp4-smoke || true
         exit 1
       fi
 
       echo "Smoke test PASSED"
+      docker rm -f myapp4-smoke || true
     '''
   }
 }
+
 
 
     stage('Docker login') {
